### ISSUE TITLE
Implement StateMachine and composite classes

### ISSUE THREAD

**Issue by shryock** [shryock/csc495-project#2]
Give our two card games, it makes sense to represent each of them with a Finite State Machine. We have discussed these in class and have many examples which we could adapt to better suit our project. This task requires creating the following classes:
- [ ] StateMachine
- [ ] State
- [ ] Setup (a subclass of State)
- [ ] Play (a subclass of State)
- [ ] Goal (a subclass of State)
- [ ] Fail (a subclass of State)
- [ ] Rule

Please see [here](https://plm18.slack.com/files/U8M1VEVT3/F98NZUTNC/CSC495_Project_Todo_List) for a proposed design of these classes.

**Comment by jessesimpson36** [comment]
I think you guys have both finished this, so I'm going to close.
